name: Build

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get VERSION Tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}"
    
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    
    - name: Get VERSION
      run: echo "VERSION=${VERSION}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=$BUILD_VERSION
      
    - name: Test
      run: dotnet test /p:Configuration=Release --no-restore --no-build --verbosity normal
