name: Build

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
    
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
          useConfigFile: true
          configFilePath: ./.github/workflows/gitversion.yml
    
    - name: Set VERSION variable
      run: echo "VERSION=${{ steps.gitversion.outputs.AssemblySemVer }}" >> $GITHUB_ENV
    
    - name: Get VERSION
      run: echo "VERSION=${VERSION}"
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${VERSION}
      
    - name: Test
      run: dotnet test /p:Configuration=Release --no-restore --no-build --verbosity normal
